### ISSUE TITLE
Categories - Show/Hide

### ISSUE THREAD

**Issue by fattox** [freeCodeCamp/discourse-meta#13]
This is just a suggestion, since Quincy mentioned things we might deem as "suboptimal".

Would it be possible to make it so that we can select which categories of the forum should be shown/hidden? At the moment, i can select either **all** _or_ **one** category at the moment.

For example, i'm already subscribed to DevTips on YouTube, so i don't need to see that category. But i'd still like to see _every other_ category. Maybe there'll be others i'd prefer to hide/show later on also.

Just something i thought might add a little QOL to the forum.

**Comment by QuincyLarson** [comment]
@fattox We are somewhat constrained by what Discourse itself will let us do. They have pretty sane defaults. It would probably be a significant amount of work build a more customized newsfeed.

Regarding DevTips, since you watch those, you should discuss them on our forum :) The purpose of the forum is not simply resource discovery, but discussion of these resources - kind of like a book club where people meet for analysis. 

As with everything else, of course, it is merely my hypothesis that people will want to discuss resources such as DevTips at length. We'll see what happens over the first few months, keep an eye on the levels of interest in this sort of resource-focused discussion.
